<?php
include_once 'Circle.php';
class Cylinder extends Circle{
    public $height;
    public function __construct($radius, $name,$height)
    {
        parent::__construct($radius, $name);
        $this->height=$height;
    }
    public function calculateArea()
    {
        return parent::calculateArea()*2 + parent::calculatePerimeter()*$this->height; // TODO: Change the autogenerated stub
    }
    public function calculateVolume(){
        return parent::calculateArea()*$this->height;
    }
}

